### ISSUE TITLE
-help output does not mention all flags

### ISSUE THREAD

**Issue by ianlancetaylor** [google/pprof#182]
The pprof executable supports flags added by `parseFlags` in internal/driver/cli.go, but not all of those flags are reported in the output of `pprof -help`.  As far as I can tell the following flags are not mentioned in the -help output:

- `-inuse_space`
- `-inuse_objects`
- `-alloc_space`
- `-alloc_objects`
- `-total_delay`
- `-contentions`
- `-mean_delay`

This was reported in the Go repository at golang/go#20734.

**Comment by aalexand** [comment]
@rauls5382 I think it's a reasonable request that these flags should display in the `-help` message, especially when pprof is invoked as part of `golang`. I think the fix is to move these from being flags to being pprof variables in `internal/driver/commands.go`?

**Comment by rauls5382** [comment]
These are compatibility options from the old pprof. They are convenient aliases for -sample_index=xxx, to be used on some specific profile types. We already have a generalized handling of sample_index so that we can say "inuse_space" as a pprof command for the right kind of profiles.

I propose to just add some text to the help files describing these legacy options in terms of the new options. I'll send a PR.
