### ISSUE TITLE
pprof --gv :gv: Unable to open the display

### ISSUE THREAD

**Issue by tanglianggithub** [google/pprof#185]
pprof ./m "/tmp/m.46192._main_-end.heap" --inuse_objects --lines --heapcheck  --edgefraction=1e-10 --nodefraction=1e-10 --gv
Using local file ./m.
Using local file /tmp/m.46192._main_-end.heap.
gv: Unable to open the display.

already installed gv.

**Comment by nolanmar511** [comment]
This seems to be intended behavior, but could possibly use more useful error messages.

When I run a similar command (different profiles, but otherwise the same), I get the following as my output, then pprof enters interactive mode:
'--inuse_objects: open --inuse_objects: no such file or directory
--lines: open --lines: no such file or directory
--heapcheck: open --heapcheck: no such file or directory
--edgefraction=1e-10: open --edgefraction=1e-10: no such file or directory
--nodefraction=1e-10: open --nodefraction=1e-10: no such file or directory
--gv: open --gv: no such file or directory
Fetched 2 source profiles out of 8'

So, things that you intend to use as flags are being interpreted as files.

When one calls pprof, one must call it with the order:
'pprof <format> [options] [binary] <source>'

So, you would need to call something like:
'pprof --gv --inuse_objects --lines --heapcheck --edgefraction=1e-10 --nodefraction=1e-10  ./m "/tmp/m.46192.main-end.heap" '

This, though, still doesn't work, because pprof doesn't have a heapcheck flag.
But the following would work:
'pprof --gv --inuse_objects --lines --edgefraction=1e-10 --nodefraction=1e-10  ./m "/tmp/m.46192.main-end.heap" '

I'm not quite sure what your use case for the heapcheck flag is, but I'd be happy to tell you if we have a feature which does something similar.

**Comment by tanglianggithub** [comment]
![image](https://user-images.githubusercontent.com/3445470/29111303-57b4db18-7d1c-11e7-9c12-e379cdaa0f76.png)

**Comment by tanglianggithub** [comment]
still not work.

**Comment by tanglianggithub** [comment]
I put --gv at the end of command for prompting 
![image](https://user-images.githubusercontent.com/3445470/29111476-fd35ebae-7d1c-11e7-9796-5a7221c4c38e.png)

**Comment by nolanmar511** [comment]
What operating system are you on? Are you ssh-ing or running virtual machine? 
The "Unable to open the display" error appears to be propagating up from somewhere, and may be related to x11 forwarding, if you are ssh-ing. 

Are you able to use the web format(--web) or dot format (--dot) instead of --gv? I'm still definitely looking into this, but these formats might provide you with a work-around.

**Comment by tanglianggithub** [comment]
ssh 
centos6.2

![image](https://user-images.githubusercontent.com/3445470/29153038-a6c82c7c-7dbd-11e7-80ba-e6b35383d0d6.png)

**Comment by nolanmar511** [comment]
I think this is an issue with your gv setup. 
The gv command opens a new window which displays a graph, so gv setup can be a bit more complicated than just installation, particularly when ssh-ing.

If you can otherwise use gv to open a new window and this problem is pprof specific, please feel free to reopen this issue.

**Comment by tanglianggithub** [comment]
How about your gv setup when ssh-ing?
I installed gv using yum without any other setups.

**Comment by nolanmar511** [comment]
1.  This isn't really my area of expertise, but you probably need to set-up x11-forwarding. GV opens a window with a display in it, and ssh-ing requires some additional set-up to make this work

2. Pprof is showing you a graph of memory allocations. It looks like its behaving as it ought to. I'm guessing at your objective, but I think the circled region of the message below is your problem.
![image](https://user-images.githubusercontent.com/14046562/29368954-069cad7a-8256-11e7-8fd7-a34e65d81aab.png)
Just so you know, symbolization converts addresses like @ 7fe752237459  into meaningful things like function names. 
pprof really does appear to be working as intended. 
If you have questions about why addresses couldn't be converted to symbols, you should probably address those to gperftools.

**Comment by tanglianggithub** [comment]
ok. Why heapcheck flag cannot be used in pprof.
shows `flag provided but not defined: -heapcheck`
don't find any useful info in your doc.

**Comment by tanglianggithub** [comment]
I used perf version pprof which worked.
Go version pprof didn't wok on gperftools 2.0 output file.

**Comment by nolanmar511** [comment]
I'm glad the perl version has worked for you.
