### ISSUE TITLE
FR: Interface to -traces output of CLI

### ISSUE THREAD

**Issue by krlmlr** [google/pprof#281]
I'm currently using the following command line to analyze the contents of a .prof file [1.prof.gz](https://github.com/google/pprof/files/1549328/1.prof.gz):

    pprof -unit us -lines -traces 1.prof

The example output on my system is [attached](https://github.com/google/pprof/files/1549330/1.prof.txt).

Unfortunately, the entire handling of the command-line arguments seems to be opaque in the internal driver class. Accessing the profile via the public [Profile class](https://github.com/google/pprof/blob/master/profile/profile.go) doesn't seem to give the same results, perhaps because some steps (e.g. symbolization) are missing.

Would you consider a public interface to the `-traces` output, that essentially does the same as the command line above, but exposes the results as a Go data structure for further processing?

I'm working on a project for [joint profiling of native and R code](https://github.com/krlmlr/gprofiler/blob/master/vignettes/proposal.Rmd#the-plan), this feature would be extremely helpful for extracting native stack traces without having to do error-prone parsing of textual output.

### What version of pprof are you using?

b8f425e

### What operating system and processor architecture are you using?

Ubuntu Linux, x86_64

### What did you do?

Tried to parse profiles via the `Driver` and the `Profile` classes, did not see how to achieve the desired result.

**Comment by nolanmar511** [comment]
I'm not sure we want to expose the output from -traces in this way, in part because we don't really have a place in our code where there is a data structure like you have described (so this wouldn't be particularly easy to expose), but also because there would be some amount of maintenance required for that feature going forward. 

However, I believe the Profile class does have the information you would need to get those results. If that does not seem to be the case, you can try using the -proto flag to generate a profile which is basically just a copy of the original (but in .pb.gz format, and which has already been processed by pprof).

In case this is useful, I'll summarize the profile format: Each sample has a field Location (which is an array of locations, so the stack). Each location in the Location array has a field Line. Line is an array, but it generally just has one element (but it can have more than one element if there are inlined funcions, in which case the last entry represents the caller which previous entries were inlined to),  and a line within the Line array has a line number in the field Line (this is an int64) and a field Function. And function has a field Name (a string, this is the function name) and a field Filename (a string).

**Comment by krlmlr** [comment]
Thanks for the heads up. I can work with the `pprof -proto` output, but this looks different from what I see with the following code snippet:

```
        in_file, err := os.Open(path)
        defer in_file.Close()

        p, err := profile.Parse(in_file)

        out_file, err := os.Create(target_path)
        defer out_file.Close()

        p.Aggregate(true, true, true, true, false)
        p.WriteUncompressed(out_file)
```

I believe the `pprof -proto` output contains output from the symbolizer that is missing when running the code above. Is there a way to add this information to the `Profile` object? I have only found `internalSymbolizer()`.

- `-proto` output: [1.prof.pb.gz](https://github.com/google/pprof/files/1555621/1.prof.pb.gz)
- Output from code above: 
[1.prof.go.pb.gz](https://github.com/google/pprof/files/1555623/1.prof.go.pb.gz)

Furthermore, it seems that the `pprof -proto` output still has mangled names, as opposed to `pprof -traces` where the names appear demangled. Does the CLI has an option to demangle names for `-proto` output?

Another question: Should I be reading legacy formats (created by gperftools) using https://github.com/google/perf_data_converter/?

**Comment by nolanmar511** [comment]
I'm not super familiar with perf_data_converter, but I believe it's intended to convert profiles generated with the Linux `perf` command to proto format which pprof uses. Pprof does handle data generated by gperftools appropriately, so I don't know that you should use per_data_converter.

Looking more at the code, I see that pprof's symbolization code is in internal/symbolize, so is not currently exposed. I don't think we want to expose this section of our code right now.
