### ISSUE TITLE
Icicle graph: inverted flame graph

### ISSUE THREAD

**Issue by narqo** [google/pprof#359]
In the comments for a recent Netflix's article about their FlameScope tool @paulirish has [noticed an interesting point][1]: in many cases, Flame Graphs are much higher than our display's height, so user has to start her's observation by scrolling to the bottom to look at the graph's root. Icicle graphs (inverted flame graph) fixes this behaviour.

To my knowledge, Chrome's performance profiler is the most widely used example of such view, while other tools / services also support it. For example [go-tourch](https://github.com/uber/go-torch) has `--inverted` flag.

In my opinion, it would be useful if pprof used inverted Flame Graph, or provided an option to transform one to another.

### What version of pprof are you using?

I use current pprof's master.

### What did you do?

```
% pprof -http :10080 cpu.prof
```

Open View → Flame Graph

[1]: https://medium.com/@paul_irish/great-stuff-bbc02caa144f

**Comment by aalexand** [comment]
I'd like that as well but I believe the flame graph component we use doesn't support that. @spiermar ?

**Comment by brendangregg** [comment]
Since it's missing from the discussion: I don't want to start reading from the root. If there's a big plateau, I want to start there, since those are the easy wins. Every time I look at a flame graph, it involves quickly understanding the overall shape, and then browsing in detail from the plateau, if it exists, or the root, if it doesn't.

It doesn't matter much since it's an endian argument at this point, and people are going to flip it and color it as they prefer, and that's fine. But I will correct the idea that I'm always starting from the root. I did reply to Paul, but it seems that Medium doesn't do threading https://medium.com/netflix-techblog/netflix-flamescope-a57ca19d47bb

**Comment by cuishuang** [comment]
interesting discussion！
