### ISSUE TITLE
Creating a release

### ISSUE THREAD

**Issue by majoros** [google/pprof#364]
Would it be possible to cut a release of this project. I am unable to get through the bureaucratic process of bringing this software into the firm I work at because there is technically no release of this project.

Thanks

**Comment by aalexand** [comment]
Cutting a release once wouldn't be a problem, having a regular process for this is more work for us which we've been trying to avoid so far. Can you just bring a version of pprof at specific commit? That's pretty much what a release would be. Alternatively, you could use Golang releases - the Go distribution includes pprof (with a modified launcher though, but for the most part that shouldn't be a problem I think).

**Comment by aalexand** [comment]
Closing, I think using a specific commit should work for you.

**Comment by wlandau** [comment]
I am developing a [profiling tool for the R language](https://github.com/r-prof/proffer), and `pprof` is the most essential piece. By far the most pressing problem with `proffer` is the [the laborious process of installing Go and then `pprof`](https://github.com/r-prof/proffer#installation), especially for typical R users who often do not have much non-R programming experience and do not always know their way around environment variables.

Re https://github.com/r-prof/proffer/issues/11, I hope to fully automate the installation of the latest stable version of `pprof`. If there were releases containing binaries for all major systems, this would be easy. In fact the famous [`blogdown`](https://github.com/rstudio/blogdown) R package has a slick [`install_hugo()`](https://github.com/rstudio/blogdown/blob/a32ebff55cad25819d2849f0d413a8df9f4a411a/R/install.R), which works because of [Hugo's releases](https://github.com/gohugoio/hugo/releases/latest).

**Comment by wlandau** [comment]
To be clear, R users have come to expect effortless installation. We have a native `install.packages()` function that downloads and installs packages from [CRAN](https://cran.r-project.org), and most packages we install this way work out of the box.

**Comment by aalexand** [comment]
@wlandau We do not have plans to publish prebuilt binaries for `pprof`. Golang distribution can be used to get those as a workaround.

**Comment by wlandau** [comment]
I just untarred [go1.14.linux-amd64.tar.gz](https://dl.google.com/go/go1.14.linux-amd64.tar.gz) and did not find the `pprof` binary in the `bin` directory. Is it supposed to be there?

**Comment by aalexand** [comment]
```
$ tar -ztvf ~/Downloads/go1.14.linux-amd64.tar.gz | grep 'pprof$'
-rwxr-xr-x root/root  14929787 2020-02-25 10:36 go/pkg/tool/linux_amd64/pprof
```

**Comment by wlandau** [comment]
Ah, thanks!
