### ISSUE TITLE
Use the webbrowser I configured as default

### ISSUE THREAD

**Issue by flying-sheep** [google/pprof#476]
The command `xdg-settings get default-web-browser` returns the correct .desktop file, so this is a place to start.

Also isn’t there some go library that deals with that stuff? Why reinvent the wheel?

**Comment by nolanmar511** [comment]
Commenting to add some background to this issue.

We have had discussions around the ordering of possible browsers in the past (#389, #402). There are some trade-offs. [Here](https://github.com/google/pprof/blob/54271f7e092ff31b10b7626fee166cbc6304e350/internal/driver/commands.go#L338-L361) is the function pprof uses to determine which browser to open. This is roughly base on go's [cmd/internal/browser Commands() function](https://github.com/golang/go/blob/0da58d076a98a0fa027ea547b2a1c35147fd6e6e/src/cmd/internal/browser/browser.go#L15-L39), with one main difference: pprof does not prioritize xdg-open, because then when the `-web` output is used, the graph isn't (or wouldn't generally) opened in a browse -- it's more likely to be opened as an svg.

**Comment by flying-sheep** [comment]
Trying a list of commands is a nice fallback, but the first attempt should be to try finding some OS-provided mechanism. They way this should be done:

1. Find a Go library that does this right
2. If you don’t find one, research the mechanisms to get the OS-configured browser for each OS you support
3. If this is called from some weird or unsupported system where step 2 fails, fall back to what you currently have

**Comment by nolanmar511** [comment]
Pull requests are always welcome and appreciated.
This probably isn't something we currently have capacity for.

**Comment by aalexand** [comment]
We don't plan making changes on this. PRs are welcome, otherwise closed.
