### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [google/pprof#486]
Greetings pprof developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run at scale all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://google.github.io/oss-fuzz/faq/ ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

**Comment by nolanmar511** [comment]
@Google-Autofuzz -- We had previously done some fuzzing in in https://github.com/google/pprof/tree/master/fuzz, but found only very trivial issues. We think this is because the API input is a protobuf.

Does OSS-Fuzz  have specialized tooling to support fuzzing protobufs well?

**Comment by nolanmar511** [comment]
This is somewhat similar to #481. [aalexand's comment](https://github.com/google/pprof/pull/481#issuecomment-521160305) there about fuzzing is very applicable here.

To quote him here, he said: "We did some fuzzing in https://github.com/google/pprof/tree/master/fuzz, there is some corpus there. The bugs we found there were quite trivial, much more trivial than expected. The reason is that the input to the API being fuzzed is a protobuf, I believe those cannot be fuzzed very well without specialized mutators like https://github.com/google/libprotobuf-mutator, but that doesn't exist for Go. So, before enabling any automated tooling, I'd like us or someone spend a bit more time proving that fuzzing is useful for pprof. Without that I'd prefer not to enable yet any continuous integration - any tool has its cost of ownership so I'd like to know benefits outweigh future time spending."
