### ISSUE TITLE
[feature] add switch to enable trim for flamegraph

### ISSUE THREAD

**Issue by YangKeao** [google/pprof#505]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

master d4f498aebedc02388a1c34ebe8dcb2e7c9e99f29

### What operating system and processor architecture are you using?

Linux 5.5.0 x86

### What did you do?

Open a protobuf file (you can download it [here](https://drive.google.com/file/d/1WnNHTWwZDp70Rywn70OBMsUUoPOvhJ04/view?usp=sharing)) and select flamegraph tab. 

### What did you expect to see?

A clean and trimmed flamegraph. Or a switch to enable trim for flamegraph.

![image](https://user-images.githubusercontent.com/5244316/74029344-6fc9f180-49e7-11ea-82bf-3ca86fd3a4f7.png)

### What did you see instead?

A huge and deep flamegraph and the trim is disabled.

However, I have tried to clone the codebase and turn on trim for flamegraph directly. The trim strategy seems too aggressive :sweat_smile: . It's definitely not acceptable to always turn on the trim. A switch may be the most acceptable solution (to leave the freedom of choice to user).

**Comment by nolanmar511** [comment]
The `-trim` flag has a [default value of true](https://github.com/google/pprof/blob/d4f498aebedc02388a1c34ebe8dcb2e7c9e99f29/internal/driver/commands.go#L165-L167), which is overridden to to be false for non-graph outputs (and which users can set to false for graph outputs).

With how `pprof` currently uses flags, it's not possible for the code to distinguish cases when `-trim` was set to true because a user specified that `-trim` should be true from cases in which `-trim` is set to true because the user did not specify a value. Given this, changes needed to allow the flame graph to be trimmed with `-trim` are likely large and are likely to  increase `pprof`'s code complexity. 

I'm also not sure right now that the value added by this feature would be sufficient to offset potential confusion (even if this feature is opt-in only).  Here's a rough outline of my perspective:
* In graph view(s), the `-trim` option results in two types of nodes being removed (approximately): nodes with small total values (so, a function where that function and all functions called by that function use few resources) and nodes with small self values (aka a function that directly use few resources) .
* For nodes with small total values: 
     * In the graph view, removing these nodes is useful, since all nodes in the graph are the same size and so are equally likely to grab attention -- removing nodes with small total values makes it possible to find the more important nodes.
     * In the flame graph view, there is less utility to removing these nodes, since nodes with small total times are narrower, so they are naturally less prominent in the flame graph.
* For nodes with small self times:
     * In the graph view, we are able to signal that these are hidden by using dashed lines to connect nodes which have hidden nodes between them. This makes it possible for users to see that nodes have been hidden and that the graph is not representing the whole call graph. Of course, this does need to be documented better than it currently is.
    * Within the flame graph, it is not possible to signal that nodes with small self times have been hidden. I worry that this could lead to some degree of the confusion.

**Comment by nolanmar511** [comment]
YangKeao@ -- Are there other changes that could be made to improve the utility of the flame graph for your workflow. 

For example, would allowing show/hide/focus/ignore to be applied to the flame graph more easily from within the web UI improve your workflow?

**Comment by aalexand** [comment]
I agree with @nolanmar511 that the [disabled trimming](https://github.com/google/pprof/blob/d4f498aebedc02388a1c34ebe8dcb2e7c9e99f29/internal/driver/flamegraph.go#L41) is intentional for the flamegraph format since there is no good way to indicate that a node or an edge was trimmed - the callgraph format goes through extra formatting to do that.

I'd recommend using focus/ignore/show/hide filters instead.
