### ISSUE TITLE
Flamegraph is incorrect when callstacks have more than 64 frames

### ISSUE THREAD

**Issue by kerrickstaley** [google/pprof#537]
### What version of pprof are you using?
I installed `pprof` today (2020-05-11) using `go get -u github.com/google/pprof`.

```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kerrick/.cache/go-build"
GOENV="/home/kerrick/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kerrick/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build198258677=/tmp/go-build -gno-record-gcc-switches"
```

### What operating system and processor architecture are you using?
Arch Linux, x86_64.

### What did you do?

1. Save [this program](https://gist.github.com/kerrickstaley/03ce209596678d8f19938cb18ff64a4a) locally as `main.cc`. This program has a series of nested functions, `main` -> `func1` -> `func2` ... -> `func62`, and `func62` calls `square_sum` which does some work and also calls `square` which does more work.
2. Compile with `g++ -g -O0 main.cc`.
3. Run with `LD_PRELOAD="/usr/lib/libprofiler.so.0" CPUPROFILE=test.cpuprof ./a.out`.
4. Launch `pprof` with `pprof -http localhost:8888 test.cpuprof`.
5. Open the "flamegraph" view.

### What did you expect to see?
The flame graph should look like this:
```
[        main        ]
[        func1       ]
[        func2       ]
[        ...         ]
[       func62       ]
[     square_sum     ]
[square]
```

### What did you see instead?
The flame graph looks like this:
```
[         main         ][   func1  ]
[         func1        ][   func2  ]
[         func2        ][   func3  ]
[          ...         ][    ...   ]
[        func61        ][  func62  ]
[        func62        ][square_sum]
[square_sum][  square  ][  square  ]
```

The behavior (looking at both this example and a larger, real example) seems to be that each call stack is shortened to 64 frames by removing the top (N - 64) frames. This makes the flamegraph output much harder to read because calls time that should be listed in a single column are spread out over multiple columns (in the real-world example there were 10+ different columns that should have all been merged into 1).

Also, there are some call stacks that look like `main` -> `func1` -> ... -> `func62` -> `square` (so `square_sum` is omitted); I think that is a different issue?

I'm not sure if this is a limitation of cpuprofile's output or of pprof's visualization.

Here is a screenshot:
![Screenshot from 2020-05-11 14-56-28](https://user-images.githubusercontent.com/184773/81617492-65c6de80-939a-11ea-8caf-39dba4b02023.png)

**Comment by nolanmar511** [comment]
This does look like the profiler used to collect the profile is truncating the stack. It seems like you're using gperftool's CPU profiler, and the stack depth of profiles collected with gperftool's CPU profiler is limited 64 frames (see [here](https://github.com/gperftools/gperftools/blob/f47a52ce85c3d8d559aaae7b7a426c359fbca225/src/profiledata.h#L104) and [here](https://github.com/gperftools/gperftools/blob/4cddede3990a96969aac9ff13ce3c8195ec91ce7/src/profiler.cc#L342)), so I'm closing this since it's not an issue with pprof.

I'm closing this issue; filing an issue with gperftools may make sense. Assuming one is mostly interested in the portion of the stack closer to the root node, using the graph view or using a "hide" filter to filter out frames near the root may be good options.
