### ISSUE TITLE
Github Actions failure on Windows

### ISSUE THREAD

**Issue by nolanmar511** [google/pprof#585]
Checking the [actions](https://github.com/google/pprof/actions?query=workflow%3Aci) tab, it looks like there are failures on the main branch starting about 7 days ago. 

This seems to be the failure (from https://github.com/google/pprof/runs/1483842328?check_suite_focus=true):
```
=== RUN   TestWebInterface
Format: "svg" not recognized. Use one of:
    proftest.go:125: unexpected error: Failed to execute dot. Is Graphviz installed?
        exit status 1
    webui_test.go:105: response for / does not match expected pattern 'F1'; actual result:
        Could not execute dot; may need to install graphviz.
    webui_test.go:105: response for / does not match expected pattern 'F2'; actual result:
        Could not execute dot; may need to install graphviz.
    webui_test.go:105: response for / does not match expected pattern 'F3'; actual result:
        Could not execute dot; may need to install graphviz.
    webui_test.go:105: response for / does not match expected pattern 'testbin'; actual result:
        Could not execute dot; may need to install graphviz.
    webui_test.go:105: response for / does not match expected pattern 'cpu'; actual result:
        Could not execute dot; may need to install graphviz.
Format: "svg" not recognized. Use one of:
Format: "svg" not recognized. Use one of:
    proftest.go:125: unexpected error: Failed to execute dot. Is Graphviz installed?
        exit status 1
    proftest.go:125: unexpected error: Failed to execute dot. Is Graphviz installed?
        exit status 1
--- FAIL: TestWebInterface (0.19s)
```

Base on [the last passing run](https://github.com/google/pprof/runs/1445501643?check_suite_focus=true), this test was previously skipped on Windows. 

```
=== RUN   TestWebInterface
    webui_test.go:88: skipping / since dot (graphviz) does not seem to be installed
```

**Comment by kalyanac** [comment]
There are some new failures in #584 too.

**Comment by wyk9787** [comment]
The failure is because `dot` failed to recognize the svg format (i.e. `-Tsvg`) on its Windows version. We are currently using `choco` to install graphviz on Windows and it seems like we are not the only one who encountered such issues: http://disq.us/p/2djll1s (this link takes a few seconds before it jumps to the right comment). I will investigate further to see whether there is any workaround. One option is to simply not installing graphviz on Windows and the currently failing test will be skipped.

The issue in #584 is the same Windows graphviz issue, not a separate one. The text at the end of that run appears in the [last passing run](https://github.com/google/pprof/runs/1445501643?check_suite_focus=true) as well.
