### ISSUE TITLE
Tag v1 Release

### ISSUE THREAD

**Issue by felixge** [google/pprof#603]
Quick question: Is there a plan to tag v1 release for this project at some point?

No worries if not, but it would help projects that import e.g. `"github.com/google/pprof/profile"` to get some guarantees about API stability.

Thank you so much for this project ❤️

**Comment by aalexand** [comment]
There are no specific plans on that. We consider the actual command line tool to be the primary interface, we are hesitant yet to commit to maintaining any API surface guarantees.

**Comment by aalexand** [comment]
Re-opening though to finalize the discussion first.

FYI - for github.com/google/pprof/profile specifically we usually try hard not to break its use since internally at Google we also have users for it. But I'm not excited to commit to provide API stability guarantees for everything that is public in the pprof packages, it's more of best effort at this point.

**Comment by felixge** [comment]
@aalexand thanks. I'm indeed only concerned about the stability of `github.com/google/pprof/profile`, so it's great to hear that it's intended to be stable.

**Comment by aalexand** [comment]
Closing. I don't expect to pin a version, but we'll do our best to keep github.com/google/pprof/profile bw compatible.
