### ISSUE TITLE
Sometimes very large flamegraphs don't render

### ISSUE THREAD

**Issue by NHDaly** [google/pprof#663]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

Git Commit: `20978b51388db0648809a2c5cc88b494c7945ec1` (https://github.com/google/pprof/commit/20978b51388db0648809a2c5cc88b494c7945ec1)

We are generating data for PProf through the julia package https://github.com/JuliaPerf/PProf.jl

### What operating system and processor architecture are you using?

MacOS Intel x86

### What did you do?

Very large profile data sometimes does not render in the flamegraphs view. It will render okay in the Graph view, but not in the Flamegraph view.

<img width="1440" alt="Screen Shot 2021-11-02 at 2 45 53 PM" src="https://user-images.githubusercontent.com/1582097/139946812-6b736a31-c0ea-4796-959d-73d1b4129fa4.png">

<img width="1440" alt="Screen Shot 2021-11-02 at 2 45 33 PM" src="https://user-images.githubusercontent.com/1582097/139946831-4e48e4d0-4e12-409d-ad05-fbd649673ea5.png">

### What did you expect to see?

I expected to see the standard flamegraph view.

### What did you see instead?

Nothing 😢 

-----

I'm sorry that I don't have a .pb.gz to upload, because the profile i currently have is from our internal, closed source codebase.

I'll try to find a reproducer profile that I can upload here with the issue. In the meantime, maybe this report is already useful.

Thanks! :)

**Comment by NHDaly** [comment]
Adding some more detail:

It appears that the issue varies by _browser_: A given profile may not render on Google Chrome, but seems to render correctly on Safari:
Chrome:
<img width="1261" alt="Screen Shot 2022-01-24 at 3 11 41 PM" src="https://user-images.githubusercontent.com/1582097/150857286-05234fb0-8ab9-4c0b-a795-f09ce12fc3fa.png">
Safari:
<img width="1324" alt="Screen Shot 2022-01-24 at 3 11 50 PM" src="https://user-images.githubusercontent.com/1582097/150857294-f77cd5cb-a7f5-4250-95ae-6a328466774f.png">

---

My details:
PProf Git Commit: 20978b51388db0648809a2c5cc88b494c7945ec1 (20978b5)
Chrome: Version 97.0.4692.71 (Official Build) (x86_64)
Safari: Version 15.2 (15612.3.6.1.8, 15612)

**Comment by NHDaly** [comment]
(but for slightly bigger profiles, they don't render in safari either)

**Comment by vilterp** [comment]
Dug into this a bit more (apologies, the only profiles I have big enough to trigger this are from a proprietary codebase).

In both Chrome and Safari I'm seeing a `Maximum call stack size exceeded` error (annoyingly without a stack trace).

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/7341/154548109-ea518b9d-da1d-4aef-8f6c-8360d06d5c7e.png">

I see that the profile data is encoded as a Javascript array inside of a `<script>` tag:

```html
<script>viewer(new URL(window.location.href), […data…])<script>
```

This leads me to believe that the stack overflow happens when trying to decode data that's too large. Safari and Chrome may have different stack size limits, perhaps explaining the difference in behavior between them.

Perhaps there's a part of the decoding/rendering algorithm which could be rewritten to use a loop instead of recursion, avoiding this overflow.

As for the screenshot in @NHDaly's comment above (filed as I was debugging this with him): I believe we got mixed up and posted a screenshot of the SVG of the graphviz view, instead of the flamegraph view. The graphviz view appears to generate its SVG server-side (with `dot`); flamegraph appears to send the data as a JS array embedded in the HTML and generate the SVG client-side with javascript; this javascript is where the problem is.

**Comment by NHDaly** [comment]
thanks for digging into this, @vilterp!! ❤️

**Comment by NHDaly** [comment]
It looks like pprof might use the `d3_flamegraph` package for rendering flamegraphs?:
https://github.com/google/pprof/blob/6f57359322fd9ce2d6dabde5b733714463416b6f/third_party/d3flamegraph/update.sh#L39

**Comment by NHDaly** [comment]
https://github.com/spiermar/d3-flame-graph

maybe we could look here

**Comment by NHDaly** [comment]
Aha!: https://github.com/spiermar/d3-flame-graph/issues/106

There must be something weird about our data... they said in https://github.com/spiermar/d3-flame-graph/issues/166 that they frequently render graphs with 2,000+ depth... I doubt we have stacks that tall, right? 🤔

**Comment by NHDaly** [comment]
If we get a bit more information, we can maybe move the conversation over to the issue in the d3-flame-graph repo? Ideally we'd have a repro, but 🤷 what can you do

**Comment by NHDaly** [comment]
This is already a lot further than i was back in November though! :)
