### ISSUE TITLE
Support Chrome JavaScript profiles

### ISSUE THREAD

**Issue by jkrems** [google/pprof#713]
The Chrome Devtools UI supports exporting CPU profiles from the performance tab in a JSON format. It would be neat if those could be analyzed in the pprof UI. There's a couple of ecosystem solutions for conversion but it would be great if it was as easy as `pprof some-file.cpuprofile`, similar to what is supported for `perf` data.

Would this be an acceptable feature for pprof?

Docs:
* File format: https://chromedevtools.github.io/devtools-protocol/1-2/Profiler/#type-Profile
* Basic usage: https://developer.chrome.com/blog/devtools-javascript-cpu-profile-migration-2/

**Comment by aalexand** [comment]
We are not taking supporting more formats as inputs in pprof - the profile.proto format is the main and the only one we focus on. I would recommend writing a separate tool to convert the Chrome Devtools profile format to a profile proto.

**Comment by nolanmar511** [comment]
Exposing code in [pprof-nodejs](https://github.com/google/pprof-nodejs) for converting V8 profiles to the profile.proto format may be a possible path forward (this may not fit in with objectives for pprof-nodejs, though, since that repo exists primarily to support Google Cloud Profiler's Node.js agent).

See https://github.com/google/pprof-nodejs/issues/84
