### ISSUE TITLE
extended dependencies because of browser test

### ISSUE THREAD

**Issue by pohly** [google/pprof#862]
### What version of pprof are you using?

Master = a892ee059fd6

### What operating system and processor architecture are you using?

Several.

### What did you do?

Update the dependencies of Kubernetes, which bumped pprof. Kubernetes has strict checks about dependencies and flagged that pprof now depends on github.com/mailru/easyjson, which is  [considered unmaintained](https://github.com/kubernetes/kubernetes/pull/121235) in Kubernetes:

```
024/05/22 09:09:54 Unwanted module "github.com/mailru/easyjson" marked in /home/prow/go/src/k8s.io/kubernetes/hack/unwanted-dependencies.json is referenced by new dependants:
2024/05/22 09:09:54    github.com/google/pprof
2024/05/22 09:09:54 !!! Avoid updating referencing modules to versions that reintroduce use of unwanted dependencies
```

As this is presumable now a dependency only because of some integration test, do you see a chance to move this dependency into a separate ~~package~~ module inside this repo?

`github.com/chromedp/chromedp` seems like pretty heavy dependency for a simple package like `pprof`.

This was introduced in https://github.com/google/pprof/pull/798.

In Kubernetes we are [probably moving ahead](https://github.com/kubernetes/kubernetes/pull/125045#issuecomment-2124865908) with updating pprof anyway, but would prefer to not add more dependencies on `github.com/mailru/easyjson`.

### What did you expect to see?

Only dependencies in go.mod which are needed to use pprof, or at least nothing that is problematic.

### What did you see instead?

`github.com/chromedp/chromedp` (large?!) and `github.com/mailru/easyjson` (unmaintained).

**Comment by ghemawat** [comment]
# Questions for pohly:

1. Can you articulate the concrete issues that would arise for Kubernetes from keeping chromedp (and others) as test-only dependencies?
2. How does K8 dependency checking work: is it Go package level, or Go module level. (If it is based on looking at go.mod and go.sum files, it is module level).

# Details

We get much better testing using chromedp, so that will be hard to remove. The good thing is that it is a test-only thing, but so should not affect any user of Kubernetes at runtime. 

Moving to a separate package may not suffice: go.mod and go.sum are per-module so the dependencies will still stick around even if things are in a separate package but in the same Go module? Though that depends on how K8 is controlling dependencies. If the K8 dependency checking is at the package level, moving to a separate package may suffice. If the K8 checking is actually looking at go.mod and go.sum files, moving to a separate package won't help.

An alternative that may work is to create a separate Go module inside the Git repository and move the chromedp based tests to that module. This will require at least some trade-offs:

1. Github actions will need to be updated to build and test multiple modules.
4. User workflows like `go test ./...` will have to change to also test other modules.

**Comment by pohly** [comment]
> Can you articulate the concrete issues that would arise for Kubernetes from keeping chromedp (and others) as test-only dependencies?

Kubernetes doesn't really distinguish between code and test dependencies. If a dependency of Kubernetes depends on `github.com/mailru/easyjson` that's a problem because it becomes a dependency of the Kubernetes code base as a whole. The practical implications are lower, but it's still a dependency and needs case-by-case analysis instead of being able to not accept it as dependency at all.

chromedp currently doesn't raise any red flags. I suppose it just makes some of the Go tooling slower because it needs to check out more code when doing dependency checks and updates.

> How does K8 dependency checking work: is it Go package level, or Go module level.

I suspect it depends and I am not an expert in that area. If you want to know the gory details, the tool which flagged the problem is https://github.com/kubernetes/kubernetes/tree/master/cmd/dependencyverifier.

> Moving to a separate package may not suffice

Right, I meant module.

**Comment by pohly** [comment]
The Kubernetes folks are [not happy](https://github.com/kubernetes/kubernetes/pull/125045#issuecomment-2128399419):
```
Direct Dependencies: 187 
-Transitive Dependencies: 328 
-Total Dependencies: 368 
+Transitive Dependencies: 334 
+Total Dependencies: 374 
 Max Depth Of Dependencies: 19 
 All dependencies:
 ```

**Comment by ghemawat** [comment]
See https://github.com/google/pprof/pull/866
